### ISSUE TITLE
Cannot merge the helpers array

### ISSUE THREAD

**Issue by curlyjason** [OrigamiStructures/foldingTime#1]
In the top of the AppController, I am trying to merge the helpers array with the base helpers array.

Not working...

**Comment by dreamingmind** [comment]
It looks like you were setting the Controllers property like this:

``` php
public $helpers .= ['Html']; // using dot equal for assignment
```

If this is what you intended and the thing you couldn't get to work there are two reasons.

First, adding arrays is done with +=

Second, performing any operation in a property declaration is not allowed. You could doe something like this in the `initialize() method if you want

**Comment by dreamingmind** [comment]
The name of the plugin in the docs does not match the actual plugin because I was planning to change the plugin name to reflect Cake's preferred naming (CakePHP). So `Cake3xMarkdown` would become `CakePHP3xMarkdown`. But I hadn't gotten this all sorted out yet.

So your controller line:

``` php
    public $helpers = [‘Form’, ‘Html’, ‘CakePHP3xMarkdown’];
```

Would not have been able to load the plugin because of the name mismatch. Also, plugin components have dot notation names -- `Plugin.Thing`. In our case, adjusting for all the name confusion I introduced in the documentation, the final proper line is:

``` php
    public $helpers = ['Form', 'Html', 'Cake3xMarkdown.CakeMarkdown'];
```

I've sorted this out and it's loading properly now.

<img width="319" alt="screen shot 2015-08-01 at 9 13 04 pm" src="https://cloud.githubusercontent.com/assets/1307216/9024698/2e3f24a8-3892-11e5-98e7-ab7d5af76780.png">
